spring.application.name=kafka-streams-demo
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.streams.application-id=orders-streams-app
spring.kafka.streams.default-key-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.default-value-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.replication-factor=1
spring.kafka.streams.properties.commit.interval.ms=1000
spring.kafka.streams.properties.cache.max.bytes.buffering=0
